/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_home_ui_RobustNativeWrapper */

#ifndef _Included_com_home_ui_RobustNativeWrapper
#define _Included_com_home_ui_RobustNativeWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_home_ui_RobustNativeWrapper
 * Method:    startWork
 * Signature: ([Ljava/lang/Object;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_home_ui_RobustNativeWrapper_startWork
  (JNIEnv *, jclass, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
